### ISSUE TITLE
You mis-spelled the word colour!

### ISSUE THREAD

**Issue by roni-estein** [ryangjchandler/color#12]
While trying to be a good neighbour, and without any pretence, I you  analyse this project, fuelled by UK labour you'll find the project dialogue distinctly US flavoured. No offence. :)

**Comment by joshhanley** [comment]
+1 to this. As an Australian, I'm also experiencing this issue 😬

**Comment by ryangjchandler** [comment]
I agree with both of you, as a Brit. Colour is the correct spelling and it pains me each time I spell it incorrectly, but CSS has ruined it for all of us so here we are, with a British version creating a library called Color.

**Comment by brayniverse** [comment]
```diff
- class Color
+ class Color extends Colour
```
